### PR TITLE
Iterate dynamic matrix

### PR DESCRIPTION
**Pull request by goldingn**
This might be of interest @jdyen: an alternative to `iterate_matrix` that lets you to pass in a function to create the matrix at each iteration. The function is written in R, but the iterations are done in tensorflow, which should be much quicker than doing the matrix creation and matrix multiplication on the greta side.

Not fully tested yet. I'd appreciate feedback!

### CODE REVIEW

**Comment by goldingn** [comment]
See [the test](https://github.com/greta-dev/greta.dynamics/blob/iterate_dynamic_matrix/tests/testthat/test_iterate_dynamic_matrix.R) for an example of how  to use it.

**Comment by goldingn** [comment]
To do:

 - [ ] add more tests
 - [ ] add example
 - [ ] add check of function argument names
 - [ ] add check of matrix dimension

**Comment by jdyen** [comment]
Looks very useful. Will check it out soon(ish).

**Comment by jdyen** [comment]
Is there a way to pass greta variables as arguments to `matrix_function`? Ideally, I'd like to set this up with matrix elements as functions of parameters and predictors (e.g. survival = f(temperature), where f() is a function to be learned).

**Comment by goldingn** [comment]
Yes, via the dots argument. The example in tests does something like this.

They need to be named, can't be lexically scoped in, and there's no checking yet to make sure you named them correctly and passed everything in, so you'll get an obscure tensorflow error if you do it wrong!

**Comment by jdyen** [comment]
Great. I will fiddle with this and see if I can break it.

**Comment by goldingn** [comment]
Thanks! Shouldn't be too hard :)

**Comment by jdyen** [comment]
Two more queries:
- why does `iter` need to be passed through to `tf_matrix_function`? Is it used for the ode solvers?
- is there a way to pass in a vector of known values (e.g. a sequence of temperatures), with the vector elements used in turn to determine the matrix at each iteration?

**Comment by jdyen** [comment]
Do those two queries answer each other? I thought iter == niter. But if it's just a counter, could I pass in a vector `x` and then explicitly call `x[iter]` in the `matrix_function`?

**Comment by goldingn** [comment]
Yes exactly, iter is a counter, and it's there so you can do just that!

**Comment by goldingn** [comment]
Though actually now that I think about it, that won't work 😬

**Comment by jdyen** [comment]
i added a hack that maybe works?
```
idx <- calculate(iter + 1)
x_to_use <- x[idx]
```

**Comment by goldingn** [comment]
I'm pretty sure that hack will always pull out the same element of `x`.

We turn the R function into a TensorFlow function via some sorcery/code-torture that mocks up the inputs as fake greta arrays, then builda a TF graph for the function operations using those. Those dummy greta arrays are arbitrarily data greta arrays full of 0s, so when you run calculate, it turns that into a scalar 0, and indexes using that.

Two possible solutions to this problem:

1. Change the input arguments to the function and `iterate_dynamic_matrix()`, so that instead of the iteration number, the function is just passed a static greta array for these additional arguments, and `iterate_dynamic_matrix()` is passed a *list* of greta arrays, one for each (possible) iteration, and on the TF side we pull out the correct greta array at each iteration and pass it in.
2. Leave this as it is, and change the extract/replace syntax in greta so that (for a subset of the ways in which we can subset in R) we can extract/replace with greta arrays. I want to do some work on that code anyway (see https://github.com/greta-dev/greta/issues/309) so that for loops are less horrifically slow.

1 will be quicker but a less nice interface. 2 is a better long-term solution, but will take more time.

If we implement 1 now, we will probably want to change it back when 2 is done. But that's not really a problem. I think I'm leaning towards option 1 so that I can implement some new models soon.

**Comment by jdyen** [comment]
I've had a go at option 1, see https://github.com/jdyen/greta.dynamics/blob/iterable_matrix/R/iterate_dynamic_matrix.R.

This passes an argument called `iterables` to `iterate_dynamic_matrix`, which is passed as a static greta array and sliced inside the `body()` function of `tf$while_loop` (in `tf_iterate_dynamic_matrix`).

This works for a simple case (`iterables` is a numeric vector) but has not been tested under more complex cases. I will put some more work into it but wanted to get your thoughts on a couple of things before I proceed:
- How should we deal with the case where `iterables` is not wanted? I've currently added a `if(missing(iterables))` clause that sets `iterables = rep(1.0, niter)` but this seems clunky. Is there a cleaner way to deal with this? Or should we make this version of `iterate_dynamic_matrix` a separate function given it's a non-standard use case?
- What if someone wants to pass multiple things to be iterated over? This current version should allow them to be passed as a padded array with indexing handled inside the user-defined matrix function, but I'd be surprised if passing a list worked (it might, I haven't tried). Is passing a list the best approach?
- Is there a preferred naming convention for the new arguments? Currently using `iterables` for the full array of things to iterate over and `iterx` for the individual slices.
- Is there a preferred order of arguments? Currently assumes first three arguments to the user-defined matrix function are `state`, `iter`, and `iterx`, with `iterables` passed as the second argument to `iterate_dynamic_matrix`.

**Pull request merged**
