### PR TITLE
Update to use latest standards + minor cleanup

### PR DESCRIPTION
**Pull request by njtierney**
- use github actions
- use roxygen markdown
- use an `.internals` file to import greta internals
- style package

### CODE REVIEW

**Review by goldingn — APPROVED** [review]
Style changes all look good from my brief read through

**Comment by njtierney** [comment]
OK cool, good to merge then? GH actions now passes, which is good!

**Comment by goldingn** [comment]
yeah, go for it!

**Comment by njtierney** [comment]
Ah, I didn't see the big ol' green badge of approval

image

**Pull request merged**
